# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HoodCity' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HoodCity
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/AdMob'
  pod 'Google-Mobile-Ads-SDK'

  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  pod 'TwitterKit'

end
